// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: meta.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ResourceKey with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ResourceKey) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ResourceKey with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ResourceKeyMultiError, or
// nil if none found.
func (m *ResourceKey) ValidateAll() error {
	return m.validate(true)
}

func (m *ResourceKey) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	if len(errors) > 0 {
		return ResourceKeyMultiError(errors)
	}

	return nil
}

// ResourceKeyMultiError is an error wrapping multiple validation errors
// returned by ResourceKey.ValidateAll() if the designated constraints aren't met.
type ResourceKeyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ResourceKeyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ResourceKeyMultiError) AllErrors() []error { return m }

// ResourceKeyValidationError is the validation error returned by
// ResourceKey.Validate if the designated constraints aren't met.
type ResourceKeyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ResourceKeyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ResourceKeyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ResourceKeyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ResourceKeyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ResourceKeyValidationError) ErrorName() string { return "ResourceKeyValidationError" }

// Error satisfies the builtin error interface
func (e ResourceKeyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sResourceKey.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ResourceKeyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ResourceKeyValidationError{}

// Validate checks the field values on DefaultResourceRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DefaultResourceRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DefaultResourceRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DefaultResourceRequestMultiError, or nil if none found.
func (m *DefaultResourceRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DefaultResourceRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for LibraryManagerName

	// no validation rules for IpAddress

	if len(errors) > 0 {
		return DefaultResourceRequestMultiError(errors)
	}

	return nil
}

// DefaultResourceRequestMultiError is an error wrapping multiple validation
// errors returned by DefaultResourceRequest.ValidateAll() if the designated
// constraints aren't met.
type DefaultResourceRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DefaultResourceRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DefaultResourceRequestMultiError) AllErrors() []error { return m }

// DefaultResourceRequestValidationError is the validation error returned by
// DefaultResourceRequest.Validate if the designated constraints aren't met.
type DefaultResourceRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DefaultResourceRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DefaultResourceRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DefaultResourceRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DefaultResourceRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DefaultResourceRequestValidationError) ErrorName() string {
	return "DefaultResourceRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DefaultResourceRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDefaultResourceRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DefaultResourceRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DefaultResourceRequestValidationError{}
